### ISSUE TITLE
Wanna help? :D

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/npm-on-ipfs#10]
Can you try registry-mirror out and share what you think of it and how would you make it better? Pleaaaase :)

You can find on the README the quickest way to test it out - https://github.com/diasdavid/registry-mirror#quick-setup-probably-all-that-you-need

Right now, our clone only has 30555 out of 499877 modules available on npm, but it is steadily growing. What this means is that modules that have dependencies that are not downloaded yet, won't be able to finish, but modules like `bignumber` which doesn't have any dependencies, are installed right away :)

How to check how many modules IPFS has available: 

```
$ ipfs files stat /npm-registry
QmVp8xYepc77iYhUdusYdSCQUH1kyK9qidpVQaoyLAP4FT
Size: 0
CumulativeSize: 27587783519
ChildBlocks: 30555
```

Thank you :)

**Comment by diasdavid** [comment]
https://github.com/diasdavid/registry-mirror/pull/11
https://github.com/diasdavid/registry-mirror/issues/7
https://github.com/diasdavid/registry-mirror/pull/6

Keep them coming :D

**Comment by Dignifiedquire** [comment]
How about something that automatically sets the registry in npm for you, e.g. if I run `registry-mirror --ipfs --set-registry` ?

**Comment by fampinheiro** [comment]
@Dignifiedquire it would be nice but I think this module should be as simple as possible.
What do you think of making the module usable by other, that way you could create a wrapper that used `registry-mirror` api and was responsible to tweak `~/.npmrc`?

**Comment by Dignifiedquire** [comment]
@fampinheiro sounds like a good idea yes
