### ISSUE TITLE
error about "npm i ipfs-npm"

### ISSUE THREAD

**Issue by shareven** [ipfs-shipyard/npm-on-ipfs#114]
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ipld-raw@^4.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ipfs'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xx/.npm/_logs/2019-07-23T10_04_54_262Z-debug.log

**Comment by andrew** [comment]
That's strange, looks like v4.0.0 is available on npm: https://www.npmjs.com/package/ipld-raw/v/4.0.0

Are you able to install that directly?: `npm i ipld-raw@4.0.0`

**Comment by shareven** [comment]
thanks，I find the reason。I should change my npm registry ：
npm config set registry https://registry.npmjs.org/
