### ISSUE TITLE
Module does not install, lots of 502 errors

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/npm-on-ipfs#115]
Mac OS X 10.14.6
NPM 6.11.2
IPFS Desktop 0.9.1

<details>
<summary>Log:</summary>

twerkworker-5935:buttons dietrich$ ipfs-npm i hypersimple
superagent: Enable experimental feature http2
👩‍🚀 Starting local proxy
🚀 Server running on port 55409
🎁 Installing dependencies with /Users/dietrich/.npm-packages/bin/npm
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsf9cc0949
Swarm listening on /ip4/127.0.0.1/tcp/55413/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/55413/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
🗂️  Loading registry index from https://registry.js.ipfs.iossion 554e45abf9cc0949
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 1 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 2 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 3 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 4 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 5 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 6 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
📴 Not connected to registry
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 1 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 2 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 3 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
📄 GET /hypersimple 200 16521mskFailedOptional: verb npm-session 554e45abf9cc0949
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 4 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:63047) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:63047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:63047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:63047) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:63047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:63047) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:63047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:63047) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:63047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 5 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 6 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
✋ Server stopped
twerkworker-5935:buttons dietrich$ which npm-ipfs
/Users/dietrich/.npm-packages/bin/npm-ipfs
twerkworker-5935:buttons dietrich$ which ipfs-npm
/Users/dietrich/.npm-packages/bin/ipfs-npm
twerkworker-5935:buttons dietrich$ ipfs-deploy 
.cache/            assets/            buttons.css        buttons.js         index.js           node_modules/      package-lock.json  stores/            views/
README.md          base.css           buttons.html       dist/              manifest.json      old-buttons/       package.json       sw.js              
twerkworker-5935:buttons dietrich$ ipfs-deploy 
.cache/            assets/            buttons.css        buttons.js         index.js           node_modules/      package-lock.json  stores/            views/
README.md          base.css           buttons.html       dist/              manifest.json      old-buttons/       package.json       sw.js              
twerkworker-5935:buttons dietrich$  ps aux | grep 'coreaudio[d]' | awk '{print $2}' | xargs sudo kill
Password:
twerkworker-5935:buttons dietrich$ npm-ipfs i hypersimple
superagent: Enable experimental feature http2
👩‍🚀 Starting local proxy
🚀 Server running on port 59293
🎁 Installing dependencies with /Users/dietrich/.npm-packages/bin/npm
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsb9a993b3
Swarm listening on /ip4/127.0.0.1/tcp/59295/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/59295/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
🗂️  Loading registry index from https://registry.js.ipfs.iossion 169f02b6b9a993b3
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 1 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 2 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 3 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 4 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 5 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io failed on attempt 6 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
📴 Not connected to registry
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 1 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 2 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 3 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
📄 GET /hypersimple 200 17714mskFailedOptional: verb npm-session 169f02b6b9a993b3
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 4 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 5 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
🚨 Request to GET https://registry.js.ipfs.io/hypersimple failed on attempt 6 - StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:70313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:70313) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:70313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to http://localhost:59293/@ungap%2fweakmap failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dietrich/.npm/_logs/2019-09-09T18_01_28_050Z-debug.log
🎁 /Users/dietrich/.npm-packages/bin/npm exited with code 1
🔏 Updating package-lock.json

</details>

**Comment by andrew** [comment]
@autonome looks like the whole registry is broken/offline: any request to https://registry.js.ipfs.io/ is throwing 502 bad gateway errors.

**Comment by andrew** [comment]
Looks like it's back up now, thanks to @achingbrain

**Comment by autonome** [comment]
502 is gone, thanks y'all. Seeing a new error now, which I reported in #116.
