### ISSUE TITLE
Offline Search

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/npm-on-ipfs#14]
Add a search command, following suggestion on https://github.com/diasdavid/registry-mirror/issues/8#issuecomment-160148743

**Comment by diasdavid** [comment]
People of npms.io 👋🏽 @satazor & @marcooliveira, can we make npms.io work offline? Perhaps just cache the indexes in IPFS and run them locally?

**Comment by marcooliveira** [comment]
Sorry for the hold up, I'm back from holidays, will discuss with @satazor and get back. He's now on holidays himself, so might only be able to discuss next week.
