### ISSUE TITLE
updated /npm-registry to: /ipfs/undefined

### ISSUE THREAD

**Issue by flipflopsimsommer** [ipfs-shipyard/npm-on-ipfs#28]
```
registry-mirror daemon
IPFS mode ON
registry-mirror [info] output dir: /npm-registry/
registry-mirror [info] listening:127.0.0.1:35943
registry-mirror [info] Updated /npm-registry to: /ipfs/undefined
```

looks like i'm not getting the right url :disappointed: any ideas why?

versions:
- ubuntu: `15.10`
- node: `5.4.0`
- npm: `3.3.12`
- ipfs: `0.4.0`

**Comment by diasdavid** [comment]
We are currently fixing this (the IPFS node responsible to release to do the IPNS name published failed us). 

Apologies for the trouble, will get back to you when this is ready and stable again.

**Comment by diasdavid** [comment]
Hi @flipflopsimsommer. @achingbrain has been doing a ton of work revamping this module. Wanna try the latest from master and let us know if it works for you? Check https://github.com/ipfs-shipyard/npm-on-ipfs
