### ISSUE TITLE
Cannot read property 'Path' of undefined

### ISSUE THREAD

**Issue by evbogue** [ipfs-shipyard/npm-on-ipfs#36]
When running the command `registry-mirror daemon --ipfs --port=9595`

I'm getting the following error:

```
TypeError: Cannot read property 'Path' of undefined
    at /usr/local/lib/node_modules/registry-mirror/src/registry-cache.js:20:20
    at /usr/local/lib/node_modules/registry-mirror/node_modules/ipfs-api/src/request-api.js:41:9
    at finish (/usr/local/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:330:16)
    at wrapped (/usr/local/lib/node_modules/registry-mirror/node_modules/wreck/node_modules/hoek/lib/index.js:867:20)
    at onReaderFinish (/usr/local/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:376:16)
    at g (events.js:273:16)
    at emitNone (events.js:85:20)
    at emit (events.js:179:7)
    at finishMaybe (_stream_writable.js:478:14)
    at endWritable (_stream_writable.js:488:3)

```

And registry-mirror quits. 

Any idea what is going wrong here?

**Comment by evbogue** [comment]
I should note that I am running the latest dev release of IPFS. I do not see any output from `registry-mirror` before the error. It hangs for a bit, and then Node quits with the error above.

**Comment by diasdavid** [comment]
@evbogue thank you for reporting this. Would you mind trying version `0.6.0`? The published version was using a old IPNS record that is no longer used.

**Comment by evbogue** [comment]
@diasdavid This error isn't showing up anymore. However, I'm getting new errors, see screenshot.

I have a feeling I might have broken something with the registry-mirror config or cache. Where does registry-mirror cache files? Perhaps I can delete them and see if it works then.

![2016-03-31-110405_1366x768_scrot](https://cloud.githubusercontent.com/assets/2468866/14180277/5b65c2fe-f730-11e5-87dc-5623358e30bc.png)

**Comment by diasdavid** [comment]
@evbogue are you using an IPFS 0.4.0 node? Check with `ipfs version`

**Comment by evbogue** [comment]
Yes. I'm using the latest dev version. IPFS works fine, as far as I can tell.

**Comment by evbogue** [comment]
Ok, I've updated to the released version of IPFS v0.4.0 and reinstalled registry-mirror. However, now I'm getting this strange error. The IPFS daemon is running and works fine for normal ipfs operations.

```
% registry-mirror daemon
{ [Error: connect QmToeN85brexqyXUnWnKfHFqhvucJPViw9AxQQkjLoULy4 failure: dial attempt failed: <peer.ID fVQ4SL> --> <peer.ID ToeN85> dial attempt failed: connection refused] code: 0 }
```

Ideas?

**Comment by diasdavid** [comment]
I've just updated it to use the latest IPFS v0.4.0 (there was a network incompatibility) and tried on my machine, you should have a positive result now. Let me know if there is any more issues.

**Comment by enjikaka** [comment]
Just got this error too. Happened after restarting OS X.

registry-mirror: 0.6.2
IPFS: 0.4.0

**Comment by enjikaka** [comment]
Error from IPFS API is not handled. The error from it is:

```
{ [Error: Could not resolve name.] code: 0 }
```

**Comment by Kubuxu** [comment]
Also getting this error.
```
TypeError: Cannot read property 'Path' of undefined
    at api.name.resolve (/usr/lib/node_modules/registry-mirror/src/registry-cache.js:20:20)
    at /usr/lib/node_modules/registry-mirror/node_modules/ipfs-api/lib/request-api.js:52:13
    at finish (/usr/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:333:16)
    at wrapped (/usr/lib/node_modules/registry-mirror/node_modules/wreck/node_modules/hoek/lib/index.js:867:20)
    at onReaderFinish (/usr/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:379:16)
    at g (events.js:286:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:487:14)
    at endWritable (_stream_writable.js:497:3)
```

**Comment by diasdavid** [comment]
Republished the IPNS record. Should be good now :)

Disclaimer: Once we get UnixFS sharding on go-ipfs, registry-mirror will become way more stable, I'll keep you all posted on that development :)

**Comment by diasdavid** [comment]
Hi @evbogue. @achingbrain has been doing a ton of work revamping this module. Wanna try the latest from master and let us know if it works for you? Check https://github.com/ipfs-shipyard/npm-on-ipfs
