### ISSUE TITLE
Inform the user they need to run a local IPFS Node on port 5001

### ISSUE THREAD

**Issue by noffle** [ipfs-shipyard/npm-on-ipfs#37]
Running `registry-mirror daemon` today /wo an IPFS node running:

```
$ registry-mirror daemon
{ [Error: Client request error: connect ECONNREFUSED 127.0.0.1:5001]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5001,
  trace: 
   [ { method: 'GET',
       url: 'http://127.0.0.1:5001/api/v0/swarm/connect?arg=%2Fip4%2F188.40.114.11%2Ftcp%2F4001%2Fipfs%2FQmZY7MtK8ZbG1suwrxc7xEYZ2hQLf1dAWPRHhjxC8rjq8E&stream-channels=true' } ],
  isBoom: true,
  isServer: true,
  data: null,
  output: 
   { statusCode: 502,
     payload: 
      { statusCode: 502,
        error: 'Bad Gateway',
        message: 'connect ECONNREFUSED 127.0.0.1:5001' },
     headers: {} },
  reformat: [Function] }
```

Great UX(tm) could be to say "hey, you need to be running a local IPFS daemon. You can do this with `ipfs daemon`. If that doesn't work, you may need to [install IPFS](https://ipfs.io/docs/install/)."

**Comment by diasdavid** [comment]
Hi @noffle. @achingbrain has been doing a ton of work revamping this module. Wanna try the latest from master and let us know if it works for you? Check https://github.com/ipfs-shipyard/npm-on-ipfs

**Comment by achingbrain** [comment]
Closing because you don't need to spin up a separate daemon any more - though you still can, if you want, with the `--ipfs-port` and `--ipfs-host` options.
