### ISSUE TITLE
Automate "update IPNS process" for Castor

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/npm-on-ipfs#4]
castor id: `QmdNc4B89DxVeiuDKRN5bWdKsAPCmekgmJMkRSdUNa7x9z`
castor multiaddr: `/ip4/37.59.33.238/tcp/4001/ipfs/QmdNc4B89DxVeiuDKRN5bWdKsAPCmekgmJMkRSdUNa7x9z`

`registry-mirror --ipfs --clone` must auto update the IPNS name each time the mirror of the registry is updated. In ipfs CLI commands, this would be:

``` bash
ipfs name publish /ipfs/`ipfs files stat /npm-registry | head -n1`
```

**Comment by diasdavid** [comment]
For quick ref
```javascript
var ipfsAPI = require('ipfs-api')('/ip4/127.0.0.1/tcp/5001')

ipfsAPI.files.stat('/npm-registry', function (err, res) {
  if (err) {
    return console.log(err)
  }
  ipfsAPI.name.publish('/ipfs/' + res.Hash, function (err, res) {
    if (err) {
      return console.log(err)
    }
  })
})
```

**Comment by diasdavid** [comment]
@whyrusleeping when doing a `ipfs name publish` on a Node with `ipfs swarm peers | wc -l` === 0, IPFS throws an error, but when we are connected to at least one Node, it doesn't anymore. There is a point in that, but the thing is that we can publish when we have 1 node, disconnect, and then connect it after, and IPNS will know to continue to provide that IPNS record. Wouldn't it make sense to just let IPNS always "publish"?

**Comment by lgierth** [comment]
> registry-mirror --ipfs --clone must auto update the IPNS name each time the mirror of the registry is updated

Does it already do that? It might make sense to update IPNS in batches.

> Wouldn't it make sense to just let IPNS always "publish"?

Agreed

**Comment by diasdavid** [comment]
part I: https://github.com/diasdavid/registry-mirror/pull/23
