### ISSUE TITLE
npm says: `error parsing json`

### ISSUE THREAD

**Issue by despairblue** [ipfs-shipyard/npm-on-ipfs#41]
I tried it with the webpack codebase and npm keeps complaining about the server response and fails in the end with `Internal Server Error`. See [this gist](https://gist.github.com/despairblue/d5023d3e0047969fc5cf311fdb86b2d4)

I think, the registry returns an `Internal Server Error` and npm tries to parse that. Thus the `Unexpected token I` error in the log.

Reproduction:

``` sh
git clone https://github.com/webpack/webpack.git
cd webpack
npm --registry=http://127.0.0.1:50321 install
```

**Comment by diasdavid** [comment]
Hi @despairblue, that is due to the fact that we do not have the entire copy of npm inside IPFS yet.

**Comment by diasdavid** [comment]
Hi @despairblue. @achingbrain has been doing a ton of work revamping this module. Wanna try the latest from master and let us know if it works for you? Check https://github.com/ipfs-shipyard/npm-on-ipfs
