### ISSUE TITLE
dial attempt failed:

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs-shipyard/npm-on-ipfs#44]
Trying to run after installing it globally.

```
$ registry-mirror daemon --clone

{ Error: connect QmToeN85brexqyXUnWnKfHFqhvucJPViw9AxQQkjLoULy4 failure: dial attempt failed: <peer.ID Nk9fWi> --> <peer.ID ToeN85> dial attempt failed: connection refused
    at /home/victor/.nvm/versions/node/v6.5.0/lib/node_modules/registry-mirror/node_modules/ipfs-api/lib/request-api.js:33:21
    at /home/victor/.nvm/versions/node/v6.5.0/lib/node_modules/registry-mirror/node_modules/ipfs-api/lib/request-api.js:47:8
    at finish (/home/victor/.nvm/versions/node/v6.5.0/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:214:20)
    at wrapped (/home/victor/.nvm/versions/node/v6.5.0/lib/node_modules/registry-mirror/node_modules/wreck/node_modules/hoek/lib/index.js:871:20)
    at ClientRequest.onResponse (/home/victor/.nvm/versions/node/v6.5.0/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:161:20)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23) code: 0 }
```

Versions

``` js
{ npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.81',
  zlib: '1.2.8' }
```

**Comment by vrogojin** [comment]
Same here

> { Error: connect QmToeN85brexqyXUnWnKfHFqhvucJPViw9AxQQkjLoULy4 failure: dial attempt failed: <peer.ID bSqCvW> --> <peer.ID ToeN85> dial attempt failed: connection refused
>     at /usr/lib/node_modules/registry-mirror/node_modules/ipfs-api/lib/request-api.js:33:21
>     at /usr/lib/node_modules/registry-mirror/node_modules/ipfs-api/lib/request-api.js:47:8
>     at finish (/usr/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:214:20)
>     at wrapped (/usr/lib/node_modules/registry-mirror/node_modules/hoek/lib/index.js:879:20)
>     at ClientRequest.onResponse (/usr/lib/node_modules/registry-mirror/node_modules/wreck/lib/index.js:161:20)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23) code: 0 }
>

**Comment by diasdavid** [comment]
@mojoaxel thanks for the ping! We will be bringing back npm-on-ipfs this quarter (check OKRs here https://github.com/ipfs/js-ipfs/blob/master/OKR.md) as one of the test vectors for the JavaScript implementation of IPFS and also because we want to have a module that is full JS so that users don't need to boot a go-ipfs node.

**Comment by diasdavid** [comment]
Hi @mojoaxel, @vrogojin. @achingbrain has been doing a ton of work revamping this module. Wanna try the latest from master and let us know if it works for you? Check https://github.com/ipfs-shipyard/npm-on-ipfs

**Comment by matthoffner** [comment]
Running the latest version from master resolved this for me, thanks.

**Comment by achingbrain** [comment]
Please re-open this issue if it happens again.
