### ISSUE TITLE
Publish latest to https://www.npmjs.com/package/ipfs-npm

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/npm-on-ipfs#51]

**Comment by achingbrain** [comment]
I don't have permissions to publish to that name.  ipfs/infrastructure#425

**Comment by diasdavid** [comment]
@achingbrain added you :) (Had added you before through their GUI, but it required me to add you 2x through the CLI to make it work)

**Comment by diasdavid** [comment]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1211152/45828221-e5c3a080-bcac-11e8-9ae5-f78140192173.png">

Yeeaaass!!! Tell everyone to use ipfs-npm to install their packages! :D
