### ISSUE TITLE
This module needs tests

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/npm-on-ipfs#53]
The last release did have some -- https://github.com/ipfs-shipyard/npm-on-ipfs/tree/ca69b25aafcf3fb285eb30f3de0f09c59c26cac9 --. 

@achingbrain what's the plan on testing this module?

**Comment by achingbrain** [comment]
It's got emojis in the logs, it doesn't need tests!

**Comment by achingbrain** [comment]
Just kidding, it has tests now.
