### ISSUE TITLE
Don't use the name `ipfs-npm` for the module?

### ISSUE THREAD

**Issue by achingbrain** [ipfs-shipyard/npm-on-ipfs#56]
Follows on from #52

I have mixed thoughts about 'npm' being in the name of this module. We're all friends but it is the trademark of a private company. npm has become synonymous with the registry which helps discovery, but the npm registry itself is an implementation of a [CommonJS Package Registry](http://wiki.commonjs.org/wiki/Packages/Registry) which can be used with yarn and whatever XYZ new registry tool.

At the very least, to comply with their [trademark policy](https://www.npmjs.com/policies/trademark) it should be `ipfs-npm-registry` but it's a bit of a mouthful so the previous name of `registry-mirror` seemed ok to me.

**Comment by diasdavid** [comment]
Thank you for bringing this up, @achingbrain. Reading through the policy, it seems we would fall into the "OK" scenario given that it is a tool to improve npm and the module is not a business at all.

I'm open to hear new names or to move back to registry-mirror. I just feel that `registry-mirror` falls short on communicating that it is an IPFS power module. Some other ideas:

- `ipfs-npm-registry` (I kind of like this one, and then the CLI can have an extra short name, like `inr`)
- `ipegistry`
- `ipnpm`

-
