### ISSUE TITLE
Sometimes registry.js.ipfs.io emits 404

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/npm-on-ipfs#57]
Currently happening for @nodeutils/defaults-deep@^1.1.0

[2018-09-11T10_54_44_752Z-debug.log](https://github.com/ipfs-shipyard/npm-on-ipfs/files/2370679/2018-09-11T10_54_44_752Z-debug.log)

**Comment by achingbrain** [comment]
I wonder if it's the scoped `@` causing the problem

**Comment by VictorBjelkholm** [comment]
Was this confirmed to only happen to scoped packages? Seeing the same issue in other places as well

**Comment by achingbrain** [comment]
@VictorBjelkholm do you have any examples or logs?
