### ISSUE TITLE
Steps to make this work on my laptop

### ISSUE THREAD

**Issue by fampinheiro** [ipfs-shipyard/npm-on-ipfs#7]
Nice work @diasdavid :) looking forward to use it as my main source for npm :package:s

For this to work I installed version 0.4.0 of ipfs and migrated my repo to version 3
### Install ipfs 0.4.0

```
cd $GO_PATH/src/github.com/ipfs/go-ipfs
git checkout dev0.4.0
go install ./cmd/ipfs
```
### Migrate ipfs fs to version 3

> After talking with @diasdavid he pointed out that since I didn't had anything locally I could have removed ~/.ipfs and initialize (`ipfs init`) ipfs again.

```
cd $GO_PATH/src/github.com/ipfs/fs-repo-migrations
git checkout 2-to-3
go install
fs-repo-migrations
```

After this changes `registry-mirror` running `npm i --registry=http://localhost:50321` hits the `registry-mirror` I am running to try to fetch the packages.

**Comment by diasdavid** [comment]
AWESOME! :D Thank you for checking it out, you will be in history as one of the persons that first did a npm install over a content addressed filesystem! :D 

Any thoughts in how to make it better? :)

**Comment by fampinheiro** [comment]
The experience you have on npm of just changing the registry is awesome :+1: 
On the ipfs set up I need some more time :) give some time and I will get back to you.
