### ISSUE TITLE
Error installing ipfs-npm

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/npm-on-ipfs#79]
```console
$ npm i ipfs-npm -g
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout mfs-sharding-support
npm ERR! error: pathspec 'mfs-sharding-support' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oli/.npm/_logs/2018-12-06T10_21_36_241Z-debug.log
```
I think a branch of js-ipfs went away but the dep ipfs-npm-registry-mirror still depends on it

https://github.com/ipfs-shipyard/ipfs-npm-registry-mirror/blob/bd1479a18aa37255b12aa7d011d6c0539bf3d16b/packages/common/package.json#L27

**Comment by achingbrain** [comment]
This should be fixed now, but beware you'll get `js-ipfs` master in your deps which could end up converting `/npm-registry` in your `mfs` into a HAMT shard.

If it gets converted the regular release of `js-ipfs` won't be able to read it until @alanshaw lands `v0.34.0`.

This should happen before Christmas but he's going to do a release candidate with the HAMT changes in it later today so people shouldn't be left too high and dry.
