### ISSUE TITLE
Dont spawn node for local operations like npm ls

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/npm-on-ipfs#95]
Things like `npm ls` and `npm -v` shouldn't trigger a spawn n dial.

```console
$ npm ls cids
👿 Spawning an in-process IPFS node using repo at /Users/oli/.jsipfs
Swarm listening on /ip4/127.0.0.1/tcp/54572/ipfs/QmPKLo7oNb6SiXUTd4fKxvnZFQXWxKzBggD9WsoFg9M4Na
🗂️  Loading registry index from https://registry.js.ipfs.io
☎️  Dialling registry mirror /ip4/35.178.192.119/tcp/10000/ipfs/Qmf8FJm6bQaLEuMyMU2wVq6BwfiUwtCNd3vz3hLMXHQA9z,/dns4/registry.js.ipfs.io/tcp/10000/ipfs/Qmf8FJm6bQaLEuMyMU2wVq6BwfiUwtCNd3vz3hLMXHQA9z
📱️ Connected to registry
👩‍🚀 Starting local proxy
🚀 Server running on port 54595
🎁 Installing dependencies with /usr/local/bin/npm
ipld-explorer-components@1.2.0 /Users/oli/Code/ipfs-shipyard/ipld-explorer-components
├── cids@0.6.0 
# trimmed
🎁 /usr/local/bin/npm exited with code 0
🔏 Updating package-lock.json
```

**Comment by achingbrain** [comment]
Fair point, we should probably spin a node up on-demand when the first registry request is received instead of at start-up.

**Comment by hacdias** [comment]
Would it be better to whitelist some commands or to open an IPFS connection when the server gets the first request? Commands like `login` will make a request to the server hence trigger connecting to the daemon although they don't need it. Or is there any other way to detect _real_ registry connections?

**Comment by achingbrain** [comment]
Sure, I meant spin up a node when a request is received that would involve IPFS-related operations like transferring a file or resolving a packument, etc - there are a bunch of endpoints we create that are just forwarded on to npm (e.g. login, detecting vulnerabilities, etc) - they would stay as they are.

**Comment by olizilla** [comment]
@achingbrain do you have a preffered solution here, or should we freestyle it? Can you drop any specific thoughts you have here so @fsdiogo can take a look.

**Comment by olizilla** [comment]
of note this issue is very related https://github.com/ipfs-shipyard/npm-on-ipfs/issues/96
